print()
print('Please enter the following:')
print()
ingverb = input('"ing" verb: ')
food = input('food (plural): ')
person = input('person: ')
verb = input('verb: ')
adjective = input('adjective: ')
noun = input('noun: ')

print()
print('Your story is:')
print()
print(f'{ingverb.capitalize()} is really hard to master, but I will teach you how. \nFirst you eat a lot of {food.lower()}. \nThis will help you be strong enough for step two. \nNext, you have to find {person.title()} and ask for help. \nThis might be hard at first, but keep trying and eventually you will succeed. \nOnce (s)he agrees to help, you have to {verb.lower()} a really {adjective.lower()} {noun.lower()}. \nIf you make it this far, your are well on your way to becoming great at {ingverb.lower()}.')
