print()
print('Please enter the following information:')
print()
name = input('First name: ')
surname = input('Last name: ')
email = input('Email address: ')
phone = input('Phone number: ')
job = input('Job title: ')
id = input('ID Number: ')
hair = input('Hair color: ')
eyes = input('Eye color: ')
month = input('Month started: ')
training = input('Advanced training complete? ')

print()
print('The ID Card is:')
print('-' * 40)
print(f'{surname.upper()}, {name.capitalize()}')
print(job.title())
print('ID:' , id)
print()
print(email.lower())
print(phone)
print()
print(f"{'Hair: ' + hair.capitalize():<25} Eyes: {eyes.capitalize()}")
print(f"{'Month: ' + month.capitalize():<25} Training: {training.capitalize()}")
print('-' * 40)
