child_meal = float(input("\nWhat is the price of a child's meal? "))
adult_meal = float(input("What is the price of an adult's meal? "))
children = int(input("How many children are there? "))
adults = int(input("How many adults are there? "))
drinks = int(input("How many drink cups would you like? ($1 each) "))
subtotal = (child_meal * children + adult_meal * adults + drinks * 1.00)

print(f"\nSubtotal: ${subtotal:.2f}")
rate = float(input("Tax rate (ie. enter 6.5 for 6.5%): "))
tip_rate = float(input("Tip rate (15% = average, 20% = excellent): "))
tax = (subtotal * rate / 100)
print(f"Sales Tax: ${tax:.2f}")
tip = (tip_rate * subtotal / 100)
print(f"Tip: ${tip:.2f}")
total = (tax + subtotal + tip)
print(f"Total: ${total:.2f}")

payment = float(input("\nWhat is the payment amount? "))
change = (payment - total)
print(f"Change: ${change:.2f}")