child_meal = float(input("\nWhat is the price of a child's meal? "))
adult_meal = float(input("What is the price of an adult's meal? "))
children = int(input("How many children are there? "))
adults = int(input("How many adults are there? "))
drinks = int(input("How many drink cups would you like? "))
subtotal = round((child_meal * children + adult_meal * adults + drinks * 1.00), 2)

print(f"\nSubtotal: ${subtotal}")
rate = float(input("Tax rate (ie. enter 6.5 for 6.5%): "))
tip_rate = float(input("Tip rate (15% = average, 20% = excellent): "))
tax = round((subtotal * rate / 100), 2)
print(f"Sales Tax: ${tax}")
tip = round((tip_rate * subtotal / 100), 2)
print(f"Tip: ${tip}")
total = round((tax + subtotal + tip), 2)
print(f"Total: ${total}")

payment = float(input("\nWhat is the payment amount? "))
change = round((payment - total), 2)
print(f"Change: ${change}")