age = int(input('\nPlease enter your age: '))
print(f'On your next birthday, you will be {age + 1} years old.')
print()
cartons = int(input('How many egg cartons do you happen to have? '))
print(f'Cool! That means you have {cartons * 12} eggs!')
print()
cookies = int(input('How many cookies are there? '))
people = int(input('How many people are there? '))
print(f'This means that each person will get {float(cookies / people)} cookies. Yum!')