import math
s = int(input('What is the length of a side of the square? '))
print(f'The area of the square is: {float(s ** 2)}')
w = int(input('What is the width of the rectangle? '))
l = int(input('What is the length of the rectangle? '))
print(f'The area of the rectangle is: {float(w * l)}')
r = int(input('What is the radius of the circle? '))
print(f'The area of the circle is: {float(math.pi * r ** 2)}')
print()
side = int(input('What is the single length value for the shapes? '))
print(f'The area of the square is {float(side ** 2)}')
print(f'The area of the circle is {float(side ** 2 * math.pi)}')
print(f'The volume of the cube is {float(side ** 3)}')
print(f'The volume of the sphere is {float(side ** 3 * math.pi * 4/3)}')